[env:attiny412]
platform = https://github.com/platformio/platform-atmelmegaavr.git
platform_packages = framework-arduino-megatinycore@https://github.com/SpenceKonde/megaTinyCore
board = ATtiny412
framework = arduino
upload_flags =
    --tool
    uart
    --device
    $BOARD
    --uart
    /dev/ttyUSB0
    -b
    $UPLOAD_SPEED

upload_protocol = custom
upload_command = python3 ${platformio.packages_dir}/framework-arduino-megaavr-megatinycore/tools/prog.py $UPLOAD_FLAGS -f$SOURCE -a write

build_flags =
  -Os
  -std=gnu++17
  -DMILLIS_USE_TIMERB=1       ; make sure Arduino doesn't steal TCA0
  -DDISABLE_TCD0_PWM=1        ; Prevent Arduino from using TCD0, we control it manually
