[env:attiny412]
platform = https://github.com/platformio/platform-atmelmegaavr.git
platform_packages = framework-arduino-megatinycore@https://github.com/SpenceKonde/megaTinyCore
board = ATtiny412
framework = arduino
upload_flags =
    --tool
    uart
    --device
    $BOARD
    --uart
    /dev/ttyUSB0
    -b
    $UPLOAD_SPEED

upload_protocol = custom
upload_command = python3 ${platformio.packages_dir}/framework-arduino-megaavr-megatinycore/tools/prog.py $UPLOAD_FLAGS -f$SOURCE -a write

build_flags =
  -mmcu=attiny412
  -Os
  -std=gnu++17
  ; -DF_CPU=3333333UL
  -DMILLIS_USE_TIMERB=1       ; make sure Arduino doesn't steal TCA0
  ; -DUSE_TCA_SPLIT=1
  ; -DARDUINO_MAIN=0            ; skip Arduino main() entirely

; build_flags =
;   -DUSE_USI_I2C=0
;   -DWIRE_INTERFACES_COUNT=0
;   ; -DMILLIS_USE_TIMERB=1
;   -DUSE_TCA_SPLIT=1
